INSERT INTO users (username, first_name, last_name, email, password, is_admin) 
VALUES ('Softoloye',
        'Promise', 
        'Morka',
        'onyekamorka06@gmail.com', 
        '$2b$12$knEx.pykp6qL1w4c7QcmOuUfkajsrO6PqsWQIBaGAcCrrMs9NmZcm',
        TRUE);

INSERT INTO exercises (name, body_part, equipment, gif_url, target)
VALUES ('Dumbbell bench press', 
        'chest', 
        'dumbbell', 
        'http://d205bpvrqc9yn1.cloudfront.net/0289.gif', 
        'pectorals'),
        ('Incline dumbbell bench press',
         'chest',
         'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0314.gif',
        'pectorals'
        ),
        ('Chest dip',
        'chest',
        'body weight',
        'http://d205bpvrqc9yn1.cloudfront.net/1430.gif',
        'pectorals'),
        ('Barbell lying triceps extension skull crusher',
        'upper arms',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0060.gif',
        'triceps'),
        ('One arm dumbbell extension',
        'upper arms',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0346.gif',
        'triceps'),
        ('Tricep extension',
        'upper arms',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1720.gif',
        'triceps'),
        ('Barbell front raise',
        'shoulders',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0041.gif',
        'delts'),
        ('Dumbbell lateral raise',
        'shoulders',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0334.gif',
        'delts'),
        ('Wide grip pull up',
        'back',
        'body weight',
        'http://d205bpvrqc9yn1.cloudfront.net/1429.gif',
        'lats'),
        ('Lat pull down',
        'back',
        'cable',
        'https://fitnessprogramer.com/wp-content/uploads/2021/02/Lat-Pulldown.gif',
        'lats'),
        ('Straight arm lat pull down',
        'back',
        'cable',
        'http://d205bpvrqc9yn1.cloudfront.net/0199.gif',
        'lats'),
        ('Machine reverse fly',
        'back',
        'Leverage machine',
        'http://d205bpvrqc9yn1.cloudfront.net/0602.gif',
        'delts'),
        ('Barbell upright row',
        'shoulders',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0120.gif',
        'delts'),
        ('Standing barbell curl',
        'upper arms',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0106.gif',
        'biceps'),
        ('Preacher curl',
        'upper arms',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1414.gif',
        'biceps'),
        ('Incline dumbbell curl',
        'upper arms',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0315.gif',
        'biceps'),
        ('Barbell full squat',
        'upper legs',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1462.gif',
        'glutes'),
        ('Dumbbell lunge',
        'upper legs',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0336.gif',
        'glutes'),
        ('45 degree leg press',
        'upper legs',
        'sled machine',
        'http://d205bpvrqc9yn1.cloudfront.net/0739.gif',
        'glutes'),
        ('Lever seated leg curl',
        'upper legs',
        'leverage machine',
        'http://d205bpvrqc9yn1.cloudfront.net/0599.gif',
        'glutes'),
        ('Lever leg extension',
        'upper legs',
        'leverage machine',
        'http://d205bpvrqc9yn1.cloudfront.net/0585.gif',
        'quads'),
        ('Barbell standing calf raise',
        'lower legs',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1372.gif',
        'calves'),
        ('Dumbbell seated calf raise',
        'lower legs',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1379.gif',
        'calves'),
        ('Barbell bench press',
        'chest',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1379.gif',
        'pectorals'),
        ('Dumbbell fly',
        'chest',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0308.gif',
        'pectorals'),
        ('Dumbbell fly',
        'chest',
        'cable',
        'http://d205bpvrqc9yn1.cloudfront.net/1269.gif',
        'pectorals'),
        ('Barbell close-grip bench press',
        'upper arms',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0030.gif',
        'triceps'),
        ('Dumbbell lying single extension',
        'upper arms',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1735.gif',
        'triceps'),
        ('Dumbbell standing alternating tricep kickback',
        'upper arms',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1739.gif',
        'triceps'),
        ('Dumbbell bench seated press',
        'shoulders',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1739.gif',
        'delts'),
        ('Cable one arm lateral raise',
        'shoulders',
        'cable',
        'http://d205bpvrqc9yn1.cloudfront.net/0192.gif',
        'delts'),
        ('Barbell standing wide military press',
        'shoulders',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/1457.gif',
        'delts'),
        ('Cable rope seated row',
        'back',
        'cable',
        'http://d205bpvrqc9yn1.cloudfront.net/1323.gif',
        'upper back'),
        ('Barbell bent over row',
        'back',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0027.gif',
        'upper back'),
        ('Smith bent over row',
        'back',
        'smith machine',
        'http://d205bpvrqc9yn1.cloudfront.net/1359.gif',
        'upper back'),
        ('Barbell deadlift',
        'upper legs',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0032.gif',
        'glutes'),
        ('Cable close grip curl',
        'upper arms',
        'cable',
        'http://d205bpvrqc9yn1.cloudfront.net/1630.gif',
        'biceps'),
        ('Dumbbell concentration curl',
        'upper arms',
        'dumbbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0297.gif',
        'biceps'),
        ('Barbell reverse curl',
        'upper arms',
        'barbell',
        'http://d205bpvrqc9yn1.cloudfront.net/0080.gif',
        'biceps');


INSERT INTO workouts (day_of_week, description, user_id)
        VALUES ('Monday', 'Chest day', 1);

INSERT INTO loggedexercises (workout_id, exercise_id, weight, unit, no_of_sets, no_of_reps)
        VALUES (1, 14, 240, 'lbs', 5, 10);



